### ISSUE TITLE
is harvest synchronisation happening?

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#100]
Or is it another full harvest?
Since the only management of harvests in this way is by adding a run 'frequency' it is difficult to say

it seems that subsequent runs after the initial harvest are much quicker, so may indicate it is sychronising, but the log available seems to be identical each time, barring timestamp, and 'Harvester History' seems to repeat it has harvested teh same again.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
