### ISSUE TITLE
Missing homepage logo graphic

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#101]
in v4.0 the logo in the top left of the 'toolbar' is missing making the back to the homepage link invisible unless hovering over the location
(compare with core geonetwork demo - works ok)
![image](https://cloud.githubusercontent.com/assets/6514963/23994045/03b2650c-0a3b-11e7-8073-926f8f3dc1cd.png)

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
