### ISSUE TITLE
Search selection button - limited to just 1000?

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#102]
The Select 'All/All in Page/None' option on Search and Contribute pages has a max of 1000 (so is not 'All')
is it possible to cconfigure this? ie higher would be useful - eg to export a zip of a ListSet or for making subscriptions

**Comment by woollattd** [comment]
found a setting that can be changed on Settings Page
need to test if it's possible to use the options for a large selection (>1000)

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
