### ISSUE TITLE
MetaInfo not working as expected

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#105]
In OpenWIS 4.0 we get these results:
eg for UENL01EHDB
![image](https://cloud.githubusercontent.com/assets/6514963/23992689/c7ffa6a0-0a35-11e7-93df-53ff701d2e44.png)

the fields have not been picked up properly

it should have this info as in OpenWIS 3.14:
![image](https://cloud.githubusercontent.com/assets/6514963/23992710/db5ea4c6-0a35-11e7-8a0b-ff88ec0fc8cc.png)

The form seems to have been copied without the correct mechanism behind it.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
