### ISSUE TITLE
Editing Metadata via Batch not as functional/useful as expected

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#106]
There is no selection method other than a search by 'metadata' not by for eg 'harvested from'
not very useful really
OK for a handful of known metadata possibly, but it's not specific enough for a larger group

![image](https://cloud.githubusercontent.com/assets/6514963/23994719/227bd27c-0a3e-11e7-857f-9524bc02ba7c.png)

...but still limited to only being able to change a few things
![image](https://cloud.githubusercontent.com/assets/6514963/23997262/8537b714-0a48-11e7-9300-32688b0f6bd6.png)

Might be better to not use this feature and use the Metadata Tool that Meteo France developed to manage metadata.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
