### ISSUE TITLE
127. v4 RET - Extend the Dissemination Harness.

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis4#16]
PN is currently assessing the state of the UKMO Harness on 3.14 and DW will do some testing. It is likely that we will need to tidy up the Harness code and fix a few minor bugs in preparation for any major changes we decide to introduce for v4. We should also review where the Harness code is kept (which repo); even though each association member tends to run their own Harness(es), we should share a repo so we can learn from each other’s code and perhaps develop some common Harness components.

PR - Let’s review the position when we have the new modular OpenWIS v4 .

**Comment by lmika-bom** [comment]
Marking this as "Do For v3" as well as doing this for v4, **so long as we don't change the harness interface**, will also work with OpenWIS v3 as well.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
