### ISSUE TITLE
88. v4 ACC - User right access on metadata editor

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis4#32]
See OpenWIS/openwis/issue#73

LM - Please confirm this works in GeoNetworks 3. If so, close this ticket.

PR - It would be useful if MF, who have real users, could mock-up their v3 user population on a v4 instance and then check they can assign rights properly, and that they work as they think they should (see issue #73). This will have to wait until we have a v4 instance worth testing. For now, I will park this under TEST and assign to MF for later when an instance is available.

**Comment by lmika-bom** [comment]
This _sort of_ works, although the approach taken is quite different than to OpenWIS 3.

- Each Metadata record belongs to a group.  For reasons that are beyond me, these groups are created within the "Users and Groups" admin section, even though "Groups" in this case do not refer to user groups.
- Each harvester is also associated with a group.  Metadata harvested from that harvester will fall under that group.
- Also, each user can be either be "Registered users", "Editors", "Reviewers" or "User administrators" for particular groups.  These are selected below the user's personal particulars.

So, a user can edit metadata if:

- The metadata belongs to that group (as determined by the harvester).
- The user is an "Editor" or a "Reviewer" of metadata of that group.

**Comment by lmika-bom** [comment]
Now, that's fine and dandy; but there are a number of (potential) issues associated with this group membership that need to be looked at:

- Within the user administration section, after selecting a group the user has particular rights to, they cannot be unassociated with any group with that right.  That is, after selecting "Sample group" for the Editor role, there is no way to deselect any groups for that role: they can no longer be non-Editors.
- I don't see any way to change the group a metadata record belongs to.
- It looks like users from a group cannot edit harvested metadata, but they can clone it and make child metadata.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
