### ISSUE TITLE
52. v4 DIS - MM4 Maintain product metadata table

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis4#8]
This task was part of the OpenWISv4/GeoNetworksv3 work package assigned to GeoCat in 2015. The documentation produced as part of that work describes the new functionality delivered.

The outcome for this feature was:

2015 status: MO/GeoCat Review; Percent complete: 0; Priority: High; Questions outstanding: 0% Done? There is a conversation with Jeremy and Leon in Redmine, but not sure how it concluded;

Extra info:

This enhancement is to be implemented as a complementary component to GeoNetwork as the functionality described herein is specific to OpenWIS. Implementation of this enhancement should be loosely coupled with the GeoNetwork code base enabling the source code for this enhancement to be maintained independently. It is highly desirable to be able to bind the capabilities described by this enhancement within GeoNetwork using deployment-time configuration rather than at compilation-time.

The OpenWIS Data Service holds a summary record for each metadata record in the catalogue. This information is stored in the Product Metadata Table and drives the processing of the Data Service on arrival and dissemination of data product instances.

The definition of the summary record, expressed as a complex type within XML Schema, is provided below:

...
Information for the summary record is located within the main metadata record according to XPath statements.

When a new metadata record is added to the OpenWIS catalogue, a corresponding entry in the Product Metadata Table shall be added using the createProductMetadata operation of the ProductMetadataService SOAP web service.

When an existing metadata record is updated within the OpenWIS catalogue, the corresponding entry in the Product Metadata Table shall be updated using the updateProductMetadata operation of the ProductMetadataService SOAP web service.

When an existing metadata record is deleted within the OpenWIS catalogue, the corresponding entry in the Product Metadata Table shall be removed using the deleteProductMetadata, deleteProductMetdataByURN or deleteProductMetadatasWithURN operations of the ProductMetadataService SOAP web service. The latter operation provides for bulk removal.

Note that the obsoleting of subscriptions associated with a deleted metadata record is undertaken by the OpenWIS Data Service.

**Comment by rogers492** [comment]
Update - scrum - 2016-11-17: GT - Not mentioned re new v4.0 as part of Kanban 81. v4 - Refactoring to improve modularity. PR - Ask GT if he is aware of this one.

**Comment by rogers492** [comment]
Update - scrum - 2017-01-17: It looks like GeoCat didn’t do anything on this and it’s not mentioned in their docs for the work they delivered (from which GT derived his list of migrated features). The requirement/spec is covered in Jeremy’s work package. GT will check to confirm that this feature was not migrated and is therefore outstanding.

**Comment by tg4444** [comment]
It appears that this has actually been implemented by the previous contractor.
The integration point was not easy to spot as it was a "JPA trigger" that is executed when CGN metadata is inserted or updated.

**Comment by tg4444** [comment]
Update on this issue:
While testing for #26 I have discovered that there is a problem when deleting metadata through the harvester, when clicking on the "Remove X records" button. 
In that case, they are only deleted from the GeoNetwork database while they remain in the OpenWIS one.

Please advise on how you want to handle this.

**Comment by rogers492** [comment]
2017-TC workshop score = 1

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
