### ISSUE TITLE
GeoNetwork documentation missing important information

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#80]
eg Harvesting info is duplicated from 2.1 version of GetNetwork.
described features are not available in GeoNetwork 3
http://geonetwork-opensource.org/manuals/trunk/eng/users/user-guide/harvesting/index.html#the-main-page

also plenty of blank pages on other features/config

GeoNetwork need to update their guides.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
