### ISSUE TITLE
Privilege mechanism issue

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#90]
only applies to metadata - not data

Metadata should be discoverable but data related to it may not be accessible due to privileges.

Setting Privileges seems to be an extra, manual, process using the Search Results page after creating metadata. It’s not based on the Group that the metadata is in. 
this also has issues due to #91 as Admins can't change this on harvested metadata.
This is very clunky and is impractical. (synchronising doesn’t apply privileges automatically) This also needs to be looked at as it has no bearing on cache data.

Also there is no mechanism for requesting privilege extension as in v3.14 
(ie add user to Institutional group)

**Comment by rogers492** [comment]
2017-TC workshop score = 1

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
