### ISSUE TITLE
Admins unable to edit harvested metadata

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#91]
can only duplicate 
would also need to change privileges after a harvest but #90

**Comment by tg4444** [comment]
Maybe I have misunderstood, but I can see that it is indeed possible to edit harvested metadata as you can see in the screenshot.

![edit-harvested-metadata](https://cloud.githubusercontent.com/assets/20536453/23955785/a08d229c-09a3-11e7-8182-fb23a2c73ccc.png)

**Comment by woollattd** [comment]
ahh
I hadn't looked there.
It seems this page is only in OpenWIS v4.0, not CGN v3.2.1
The 'Contribute' page should also allow editing, but it doesn't.
It does have the options available for non-harvested metadata but it doesn't for harvested metadata

For the same metadata we only get the duplicate option
![image](https://cloud.githubusercontent.com/assets/6514963/23959056/f6a38b38-099b-11e7-832d-b536d752f222.png)

**Comment by woollattd** [comment]
I also notice that the 'search' check boxes are not available on the 'new' page as well as no selection boxes, which would make administration of the metadata a very slow process and impractical, as it would need to be done one by one instead of in batches.

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
