### ISSUE TITLE
what is actual schema used in v4.0? is it ISO19139 or ISO 19115

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#92]
Metadata records in GeoNetwork are described by a schema. The schema sets out the structuring of the metadata record and provides all the ancillary data and functions to use the schema in GeoNetwork.
I notice there is a discrepancy in GeoNetwork…. Supposed to be ISO19139 but shows ISO19115? So which is it?
There is a slight difference - ISO 19139 is an XML encoding of ISO 19115 with additions from ISO 19119 to cover metadata for services that provide geospatial data

![image](https://cloud.githubusercontent.com/assets/6514963/23994203/b913fd52-0a3b-11e7-876e-6c23299bddbc.png)

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
