### ISSUE TITLE
How is validation carried out on Metadata?

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#93]
it does appear to do something at harvest but none of the harvested metadata is marked as validated in management screen (Contribute)
this needs to be done as a manual process after harvesting? not sure how long would this take?
also... is it done to ISO19139? see isse #92 

the system is showing that the metadata has **never** been validated:
![image](https://cloud.githubusercontent.com/assets/6514963/23993738/b2817ffc-0a39-11e7-8e7b-0d697c3df4d8.png)

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
