### ISSUE TITLE
how is ListSet exposed to other GISCs?

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis4#95]
What about harvesting from this system?
http://cgn-openwis.eurodyn.com/geonetwork/srv/eng/oaipmh?verb=ListSets 
Compare with 
https://gisc.metoffice.gov.uk/openwis-user-portal/srv/oaipmh?verb=ListSets

totals aren't shown

**Comment by rogers492** [comment]
Development of OpenWISv4 is stopped.
